name: boilerplate
description: An absolute bare-bones nuts application.
# version: 1.0.0
#homepage: https://www.example.com
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  nuts: ^2.1.4
  observable_ish: ^2.1.4

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
